name: Perl CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: ["ubuntu-latest", "macos-latest", "windows-latest"]
        perl: ["5.10", "5.14", "5.16", "5.36", "5.40"]
        exclude:
          - runner: windows-latest
            perl: 5.10
    name: Perl ${{ matrix.perl }} on ${{ matrix.runner }}
    
    steps:
    - uses: AAHAZRED/install-perl-module@v0.04
      with:
        os: ${{ matrix.runner }}
        perl: ${{ matrix.perl }}
        token: ${{ secrets.GITHUB_TOKEN }}
