name: Perl CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version: ['5.12', '5.32', '5.34', '5.36']  # Perl-Versionen anpassen

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}

      - name: Install dependencies
        run: |
          cpanm --installdeps --notest .

      - name: Run tests
        run: |
          perl Makefile.PL
          make
          make test
