name: Perl CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# https://github.com/shogo82148/actions-setup-perl

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest"]
        perl: ["5.10"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm ExtUtils::MakeMaker
      - run: cpanm ExtUtils::ParseXS
      - run: cpm install Test::More
      - run: cpanm App::cpanminus
      - run: cpanm --installdeps --verbose .
      - run: prove -lv t

