name: Perl CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        perl: ["5.38", "5.36", "5.34"]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm --installdeps .
      - run: prove -lv t


#  # Taken from https://github.com/FGasper/perl-github-action-tips
# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       fail-fast: false
#       matrix:
#         perl-version: ['5.10', '5.32', '5.34', '5.36']  # Perl-Versionen anpassen

#     container:
#       image: perldocker/perl-tester:${{ matrix.perl-version }}

#     steps:
#       - uses: actions/checkout@main
#         with:
#             submodules: recursive
#       - run: perl -V
#       - run: cpanm --notest --installdeps --verbose .
#       - run: perl Makefile.PL
#       - run: make
#       - run: prove -wlvmb t
