name: Perl CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

 # Taken from https://github.com/FGasper/perl-github-action-tips
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version: ['5.10', '5.32', '5.34', '5.36']  # Perl-Versionen anpassen

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@main
        with:
            submodules: recursive
      - run: perl -V
      - run: cpanm --notest --installdeps --verbose .
      - run: perl Makefile.PL
      - run: make
      - run: prove -wlvmb t
