name: Perl CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# https://github.com/shogo82148/actions-setup-perl

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: ["ubuntu-latest", "macos-latest", "windows-latest"]
        perl: ["5.10", "5.14", "5.16", "5.36", "5.40"]
        exclude:
          # This combination causes problems
          - runner: windows-latest
            perl: 5.10
    name: Perl ${{ matrix.perl }} on ${{ matrix.runner }} -  composite action
    uses: AAHAZRED/install-perl-module
    with:
      os: ${{ matrix.runner }}
      node: ${{ matrix.perl }}

